### ISSUE TITLE
Syntax error in parallel.py when importing peartree

### ISSUE THREAD

**Issue by doman84** [kuanb/peartree#117]
Hi,

I have this kind of error after using `import peartree as pt`

```
  File "C:\anaconda2\lib\site-packages\peartree\parallel.py", line 18
    target_time_start: int,
                     ^
SyntaxError: invalid syntax
```

Looks like some very basic problem, but I'm not very well in python :)

**Comment by kuanb** [comment]
Thanks @doman84 for your question. Please also include your version of Python. peartree uses type annotations, and this not supported in earlier versions of Python 3, as well as Py2.

You can see release notes re: type annotations, here: https://docs.python.org/3/whatsnew/3.6.html

**Comment by kuanb** [comment]
Here's a StackOverflow question with more discussion that may assist you: https://stackoverflow.com/questions/51203670/syntaxerror-invalid-syntax-with-variable-annotation

**Comment by doman84** [comment]
Ok, sorry for that. I miss information that 3.6 version of Python is needed :)

Anyway - great job with this project. I'm one of the leaders of great group influencing on public transport in biggest polish metropolis. Generally our activities are mainly happenings, but we try do the analysis as well and all kind of tools help us a lot.

**Comment by kuanb** [comment]
Thanks, please feel free to leave any additional questions as you  perform your analysis. Happy to help. :)
