### ISSUE TITLE
UserWarning: Boolean Series key will be reindexed to match DataFrame index.

### ISSUE THREAD

**Issue by bryanculbertson** [kuanb/peartree#165]
I just upgraded to Pandas `1.2.0` on Python `3.8.5` and I am getting a warning from Pandas:

> UserWarning: Boolean Series key will be reindexed to match DataFrame index.

At this line of code:
https://github.com/kuanb/peartree/blob/254207ba759d82a1d66f84287075ce1f8d093463/peartree/parallel.py#L127

I think this is because the filter is using a different Dataframe from the Dataframe being filtered.

**Comment by bryanculbertson** [comment]
@kuanb I don't know this code, but the fix may be to change `constraint_2` to use `stop_times_by_stop` instead: 
```
constraint_2 = (stop_times_by_stop.direction_id == direction)
direction_subset = stop_times_by_stop[constraint_2]
```

https://github.com/kuanb/peartree/blob/254207ba759d82a1d66f84287075ce1f8d093463/peartree/parallel.py#L126

**Comment by bryanculbertson** [comment]
Same warnings occur for Pandas `1.1.5`

**Comment by kuanb** [comment]
Thanks, yeah I think the solution would be to actually access the boolean list as a numpy array rather than a pandas Series.

**Comment by kuanb** [comment]
I believe [this](https://github.com/kuanb/peartree/pull/167) should be able to change it.

**Comment by bryanculbertson** [comment]
Fixed by https://github.com/kuanb/peartree/pull/166
