### ISSUE TITLE
Create a `0.6.4` release for #166

### ISSUE THREAD

**Issue by bryanculbertson** [kuanb/peartree#168]
Can you tag a release and upload to PyPi so I can get the fix for https://github.com/kuanb/peartree/pull/166 ?

Thanks!

**Comment by kuanb** [comment]
Yep sorry for the delay @bryanculbertson 

Just tagged the release and updated https://pypi.org/project/peartree/

**Comment by bryanculbertson** [comment]
Woohoo. Thanks @kuanb !
