### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'MTA NYCT'

### ISSUE THREAD

**Issue by ghost** [kuanb/peartree#172]
Hi ! 

I downloaded several gtfs and every time I tried to `feed = pt.get_representative_feed(gtfs)` I got `ValueError: invalid literal for int() with base 10: 'MTA NYCT'` 
This error comes from this line : `df = pd.read_csv(path, dtype=np.unicode, encoding=encoding, index_col=False)` in `\partridge\gtfs.py` because `trip_id` and `service_id` are not `int`  but `str`.

Is it normal because every gtfs I tried have `trip_id` and `service_id`  as `str ` even in the example : http://kuanbutts.com/2017/12/13/betweenness-centrality-peartree/

Do I have to make modifications to GTFS before applying feed method ?

Thanks !

**Comment by invisiblefunnel** [comment]
There is a [bug in numpy v1.20.0](https://github.com/numpy/numpy/issues/18287). Upgrade to numpy v1.20.1 to get the fix. More discussion here: https://github.com/remix/partridge/issues/68.

**Comment by kuanb** [comment]
Thanks @invisiblefunnel 

Captured upgrade in the following ticket: https://github.com/kuanb/peartree/issues/173
