### ISSUE TITLE
Traversing graph

### ISSUE THREAD

**Issue by Dabendorf** [kuanb/peartree#174]
Hey,
I am a bit missing a documentation for the project.
Is there an easy way to traverse the graph or to get a list of all pairs of nodes and their shortest distances between each other?

Many greetings,
Lukas

**Comment by kuanb** [comment]
Once the graph is initialized, it's a networkx object and you can use any/all methods available through that library. I would refer to that documentation for accomplishing tasks such as what you described:

https://networkx.org/
