### ISSUE TITLE
[feature] Support export to graph-tool

### ISSUE THREAD

**Issue by kuanb** [kuanb/peartree#2]
Per this [tweet](https://twitter.com/UrbanDemog/status/936214920093405184) by GH user @rafapereirabr: A request to support [graph-tool](https://graph-tool.skewed.de).

A [Gist](https://gist.github.com/bbengfort/a430d460966d64edc6cad71c502d7005) does exist to support graph-tool conversion from NetworkX.

Potential snafus would be increasing the complexity of the installation of this library by supporting graph-tool. One way around this would be to make the installation optional (akin to how GeoPandas treats Rtree).

**Comment by rafapereirabr** [comment]
Thanks for putting me in the loop, Kuan.

**Comment by kuanb** [comment]
Just leaving a thought here. There is the potential that implementing graph-tool would open up the possibility for accessibility-style analyses to be performed within this library, thus providing a potentially more stable replacement to Pandana.

**Comment by kuanb** [comment]
Another update: Here's a nice resource for converting out from NetworkX to graph-tool. This is the article that was paired with the Gist from the top of this issue, actually: [Blog post.](https://bbengfort.github.io/snippets/2016/06/23/graph-tool-from-networkx.html)

**Comment by rafapereirabr** [comment]
Adding two cents here: both `OSMnnx`  and `networkx` allow one to save a graphs as `GraphML` file, which I believe can be easily read by graph-tool as a planar graph if I'm not mistaken.

**Comment by kuanb** [comment]
Just a note that this is now possible (see this blog post for more information: http://kuanbutts.com/2018/08/17/peartree-to-graph-tool/)

I will be incorporating this update into the library, as well as support within the Docker container, shortly.

Performance gains are huge!

**Comment by rafapereirabr** [comment]
Hi @kuanb , It's great to see you're making so much progress with such performance gains. I'm really glad to see the directions the project is taking. 

Excited to hear that peartree + graph-tool could become a really efficient replacement for [Pandana](https://github.com/UDST/pandana)/[urbanaccess](https://github.com/UDST/urbanaccess), [OpenTripPlanner](https://github.com/opentripplanner/OpenTripPlanner) and other routing open-source packages that work with GTFS data

**Comment by kuanb** [comment]
peartree now supports interfacing with graph-tool (outbound, export)
